#page title
page_title                                : ReViiV                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1557588292                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/us/app/reviiv/id1557588292  # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.martysoft.breather  # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/icon.jpg                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : ReViiV                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Therapy for Rapid "Long Covid" Relief & Recovery!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : MartySoft, LLC
your_link                                 :
your_city                                 :
email_address                             :
facebook_username                         :
instagram_username                        :
twitter_username                          :
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Created by a Long Covid Patient
    description                           : May help with Fatigue, Loss of Taste & Smell, Brain Fog, Shortness of Breath & more.  Results often in days!
    fontawesome_icon_name                 : user-md

  - title                                 : Includes Daily Guided Exercises & Weekly Tests
    description                           : ReViiV includes 16 stages of guided daily beathing to steadily improve your breathing quality & capacity.
    fontawesome_icon_name                 : calendar-week

  - title                                 : Track Your Progress, See the Improvement!
    description                           : ReViiV includes weekly progress tests and graphs to measure your progress.
    fontawesome_icon_name                 : chart-bar

  - title                                 : Auto-Intensity & Advanced Controls
    description                           : ReViiV automatically adjusts exercise intensity to match your breathing level and progress.
    fontawesome_icon_name                 : calculator

  - title                                 : Includes Additional Long Covid Resources
    description                           : ReViiV includes detailed guides and additional Long Covid information and tips to ensure optimum results.
    fontawesome_icon_name                 : virus-covid

  - title                                 : Based on Research & Trials by Long Covid Experts
    description                           : Special thanks to our test patients & the Post-Covid care team at Mt. Sinai Hospital for their leading Long Covid work.
    fontawesome_icon_name                 : microscope

  - title                                 : Limited Time, Intro Price!
    description                           : ReViiV is over 60% off its regular price to celebrate its global launch!  Download now on iOS & Android.
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : Therapy Anywahere in Minutes a Day 
    description                           : ReViiV is safe, 100% natural and can be done nearly anywhere in minutes a day using just your mobile phone.
    fontawesome_icon_name                 : briefcase-medical

  - title                                 : 10% of Proceeds Go to Long Covid Research!
    description                           : Help find a cure with 10% of proceeds going to support Long Covid research!
    fontawesome_icon_name                 : hand-holding-dollar

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
