#page title
page_title                                : ReViiV                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1557588292                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/us/app/reviiv/id1557588292  # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.martysoft.breather  # Enter Google Play Store URL.
presskit_download_link                    : https://reviiv.me/assets/ReViiVPressKit-2022.zip   # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
# Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/icon.jpg                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : ReViiV                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : "Experience Long COVID Relief with ReViiV!<br><br>Harness 8 powerful techniques with 5-minute guided daily exercises for fast relief & ongoing, steady recovery."

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : MartySoft, LLC
your_link                                 :
your_city                                 :
email_address                             :
facebook_username                         :
instagram_username                        :
twitter_username                          :
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Immediate Symptom Relief!
    description                           : "Harness 8 scientfically backed techniqes for rapid relief, often starting within 24 hours. (See: <a href=\"/howitworks/\">How ReViiV works</a>)"
    fontawesome_icon_name                 : briefcase-medical

  - title                                 : Extensive Symptom Support
    description                           : Aids with fatigue, muscle/joint pain, taste/smell loss, brain fog, breathlessness, insomnia & more.
    fontawesome_icon_name                 : user-md

  - title                                 : Fast Tracked by the FDA!
    description                           : The <a href="https://www.theatlantic.com/magazine/archive/2021/04/unlocking-the-mysteries-of-long-covid/618076/?utm_source=newsletter&utm_medium=email&utm_campaign=atlantic-daily-newsletter&utm_content=20210308&silverid-ref=NDQ1Mzc4MzU1NDgxS0" target="_blank">FDA has acknowledged</a> the therapy's effectiveness for treating Long Covid and will not require approval.
    fontawesome_icon_name                 : user-md
    
  - title                                 : Backed by Science & Trials
    description                           : Based on techniques tested on Long COVID patients at <a href="https://www.theatlantic.com/magazine/archive/2021/04/unlocking-the-mysteries-of-long-covid/618076/?utm_source=newsletter&utm_medium=email&utm_campaign=atlantic-daily-newsletter&utm_content=20210308&silverid-ref=NDQ1Mzc4MzU1NDgxS0" target="_blank">Mt. Sinai Center for Post-COVID Care</a>.
    fontawesome_icon_name                 : chart-bar

  - title                                 : Personalized & Progressive Exercises
    description                           : Progress through 16 stages, tailored to your fitness level, for steady, ongoing improvement.
    fontawesome_icon_name                 : calculator

  - title                                 : Created by a Long COVID Patient
    description                           : Co-created by a Long-Hauler through leading post-viral research and trials.
    fontawesome_icon_name                 : hand-holding-heart
    
  - title                                 : Accessible & Safe
    description                           : Safe, 100% natural therapy, requiring just minutes a day with clear guides and visual aids.
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : See The Results!
    description                           : Track your improvement with weekly assessments and performance graphs.
    fontawesome_icon_name                 : hand-holding-heart

  - title                                 : Now Available Globally
    description                           : Download ReViiV Free on any iOS & Android device worldwide.
    fontawesome_icon_name                 : star


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
